### ISSUE TITLE
Add rpc cmd to list all addresses in user wallet

### ISSUE THREAD

**Issue by xdwangchn** [FissionAndFusion/FnFnCoreWallet#12]
listaddress
Returns a json array with objects.
object format：
For pubkey address
  address ：base32encoded address ，string；
  type ：“pubkey”
  pubkey ：pubkey hex string
For template address
  address ：base32encoded address，string
  type ：template type name
  context ：the same as “validateaddress”

**Comment by ouyun** [comment]
This issue has been resolved by task #25
